/**
 * TEST-doc-export — Graph → JSON/Markdown re-exporter (CR-GC-113).
 *
 * Verifies the single SSOT sync path:
 *   1. ROUND-TRIP: import the committed SSOT JSON into a REAL disk Kuzu harness,
 *      pull the IN-MEMORY authoritative graph (harness.getGraph() — NOT a fresh
 *      Kuzu reload, which is lossy), exportGraphJson, assert BYTE-IDENTICAL to
 *      the committed file. Output is asserted in memory only — the repo SSOT is
 *      never written.
 *   2. DETERMINISM: exportGraphJson and exportMarkdown each produce byte-identical
 *      output across two calls.
 *   3. exportMarkdown emits the GENERATED header and is non-empty for every view.
 *
 * Real KuzuAdapter on a mkdtemp disk path — no mocks, never :memory:.
 */
import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { mkdtempSync, rmSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { KuzuAdapter } from '@sigloch/graph-cypher-wasm';
import { SE_DESCRIPTOR } from '@sigloch/graph-api-core';
import type { Graph } from '@sigloch/graph-api-core';
import { GraphCodeHarness } from '../src/harness.js';
import {
  exportGraphJson,
  exportMarkdown,
  MARKDOWN_VIEWS,
  MarkdownViewSchema,
  VIEW_FILENAMES,
} from '../src/exporter.js';
import type { HarnessConfig } from '@sigloch/contracts/harness';

const REPO_ROOT = join(__dirname, '..');
const GRAPH_JSON = join(REPO_ROOT, 'docs/graph/graphcode.graph.json');

function makeConfig(repoRoot: string): HarnessConfig {
  return {
    repoRoot,
    scope: { workspaceId: 'test-ws', systemId: 'graphcode' },
    consumerType: 'system',
    preCommitTimeout: 5000,
  };
}

describe('exportGraphJson / exportMarkdown (TEST-doc-export)', () => {
  let tmp: string;
  let harness: GraphCodeHarness;
  let graph: Graph;
  let committedRaw: string;

  beforeAll(async () => {
    committedRaw = readFileSync(GRAPH_JSON, 'utf8');
    tmp = mkdtempSync(join(tmpdir(), 'graphcode-export-'));
    const storage = new KuzuAdapter({ ontology: SE_DESCRIPTOR, path: join(tmp, 'kuzu') });
    // lockDir = temp store dir, not repoRoot/.graphcode (a live dev server owns that, CR-GC-218).
    harness = new GraphCodeHarness(makeConfig(REPO_ROOT), storage, undefined, { lockDir: tmp });
    await harness.initialize();
    // seedFromJson() loads the committed SSOT via importGraph and sets the
    // in-memory authoritative graph (full attribute fidelity). getGraph() returns
    // THAT working copy — not a lossy Kuzu reload.
    await harness.seedFromJson();
    graph = harness.getGraph();
  });

  afterAll(async () => {
    await harness.close();
    rmSync(tmp, { recursive: true, force: true });
  });

  it('ROUND-TRIP: exportGraphJson of the in-memory SSOT is byte-identical to the committed file', () => {
    const exported = exportGraphJson(graph);
    // Byte-identical: exporter is the exact inverse of importGraph and the
    // committed file is already in canonical `JSON.stringify(_, null, 2) + "\n"` form.
    expect(exported).toBe(committedRaw);
    expect(Buffer.from(exported).equals(Buffer.from(committedRaw))).toBe(true);
  });

  it('ROUND-TRIP preserves lossy-in-Kuzu attributes (status/kinds/method/nested attributes)', () => {
    const exported = JSON.parse(exportGraphJson(graph)) as {
      elements: Array<Record<string, unknown>>;
    };
    const byId = new Map(exported.elements.map((e) => [e.id as string, e]));
    // status — dropped on a raw Kuzu reload, present here.
    expect(byId.get('MOD-docs')?.status).toBeDefined();
    // kinds — REQ-only top-level attr.
    expect(byId.get('REQ-doc-export')?.kinds).toBeDefined();
    // method — TEST-only top-level attr.
    expect(byId.get('TEST-doc-export')?.method).toBeDefined();
    // zodDefinition — FLATTENED to a top-level attribute (CR-GC-219): the old nested
    // `attributes.zodDefinition` artifact is gone; the value is preserved one level up.
    const schema = byId.get('SCHEMA-mutate-command') as { attributes?: unknown; zodDefinition?: unknown };
    expect(schema?.zodDefinition).toBeTypeOf('string');
    expect(schema?.attributes).toBeUndefined();
  });

  it('DETERMINISM: exportGraphJson is byte-identical across two calls', () => {
    expect(exportGraphJson(graph)).toBe(exportGraphJson(graph));
  });

  it('DETERMINISM: exportMarkdown is byte-identical across two calls (every view)', () => {
    for (const view of MARKDOWN_VIEWS) {
      expect(exportMarkdown(graph, view)).toBe(exportMarkdown(graph, view));
    }
  });

  it('exportMarkdown emits the GENERATED header and is non-empty for every view', () => {
    for (const view of MARKDOWN_VIEWS) {
      const md = exportMarkdown(graph, view);
      expect(md.length).toBeGreaterThan(0);
      expect(md).toContain('GENERATED by @sigloch/graphcode exportMarkdown');
      expect(md).toContain('DO NOT HAND-EDIT');
      expect(md).toContain('docs/graph/graphcode.graph.json');
      // No `()` or `|` inside any rendered Mermaid label (we emit no Mermaid, so
      // assert there is no mermaid fence at all — keeps the blank-diagram hazard out).
      expect(md).not.toContain('```mermaid');
    }
  });

  it('the foundation views mirror FLOW-export-request (spec/architecture/cr-list/references)', () => {
    // The four foundation views are still present (CR-GC-220 ADDS to them, no parallel path).
    for (const v of ['architecture', 'cr-list', 'references', 'spec']) {
      expect([...MARKDOWN_VIEWS]).toContain(v);
    }
    // schema rejects unknown views.
    expect(() => MarkdownViewSchema.parse('bogus')).toThrow();
  });

  it('exportMarkdown reflects the graph: cr-list lists CR nodes, references lists traces', () => {
    const crList = exportMarkdown(graph, 'cr-list');
    const crCount = graph.nodes.filter((n) => n.type === 'CR').length;
    expect(crCount).toBeGreaterThan(0);
    // CR-GC-113 itself must appear in the CR view.
    expect(crList).toContain('CR-GC-113');

    const refs = exportMarkdown(graph, 'references');
    // A known trace from the graph appears in the references view.
    const firstEdge = graph.edges[0];
    expect(refs).toContain(firstEdge.sourceId);
    expect(refs).toContain(firstEdge.targetId);
  });

  // -------------------------------------------------------------------------
  // CR-GC-220 — the 12 deterministic SE-artifact render views.
  // -------------------------------------------------------------------------

  const CR220_VIEWS = [
    'srs',
    'nfr',
    'rtm',
    'icd',
    'testconcept',
    'testmatrix',
    'intplan',
    'changelog',
    'fmea',
    'conops',
    'trade',
    'implplan',
  ] as const;

  it('CR-GC-220: schema accepts all 12 new views plus spec (16 total)', () => {
    for (const v of CR220_VIEWS) expect(() => MarkdownViewSchema.parse(v)).not.toThrow();
    expect(MARKDOWN_VIEWS.length).toBe(16);
    expect([...MARKDOWN_VIEWS]).toContain('spec'); // full dump kept
  });

  it('CR-GC-220: every new view renders non-empty with the GENERATED header', () => {
    for (const v of CR220_VIEWS) {
      const md = exportMarkdown(graph, v);
      expect(md.length).toBeGreaterThan(0);
      expect(md).toContain('GENERATED by @sigloch/graphcode exportMarkdown');
      expect(md).toContain('DO NOT HAND-EDIT');
      expect(md).not.toContain('```mermaid');
    }
  });

  it('CR-GC-220: every new view is byte-identical across two renders (determinism)', () => {
    for (const v of CR220_VIEWS) {
      const a = exportMarkdown(graph, v);
      const b = exportMarkdown(graph, v);
      expect(Buffer.from(a).equals(Buffer.from(b))).toBe(true);
    }
  });

  it('CR-GC-220: SRS (REQ-slice, 29148) ≠ model spec (full dump)', () => {
    const srs = exportMarkdown(graph, 'srs');
    const spec = exportMarkdown(graph, 'spec');
    expect(srs).not.toBe(spec);
    // SRS carries the specification scaffolding; spec is a type-grouped dump.
    expect(srs).toContain('System Requirements Specification');
    expect(srs).toContain('## 4  Requirements');
    expect(spec).toContain('Modell-Spezifikation');
    expect(spec).not.toContain('System Requirements Specification');
    // SRS is a REQ slice: no SYS/MOD/FUNC type sections like the full dump has.
    expect(spec).toContain('## FUNC');
    expect(srs).not.toContain('## FUNC');
  });

  it('CR-GC-220: NFR view only lists non-functional REQ', () => {
    const nfr = exportMarkdown(graph, 'nfr');
    const nonFunc = graph.nodes.filter(
      (n) => n.type === 'REQ' && Array.isArray(n.attributes['kinds']) &&
        (n.attributes['kinds'] as string[]).includes('non-functional'),
    );
    expect(nonFunc.length).toBeGreaterThan(0);
    expect(nfr).toContain(nonFunc[0].uid);
    // A purely functional REQ (kinds without non-functional) must NOT appear.
    const func = graph.nodes.find(
      (n) => n.type === 'REQ' && Array.isArray(n.attributes['kinds']) &&
        (n.attributes['kinds'] as string[]).includes('functional') &&
        !(n.attributes['kinds'] as string[]).includes('non-functional'),
    );
    if (func) expect(nfr).not.toContain(func.uid);
  });

  it('CR-GC-220: TestConcept shows System E2E as ✗ MISSING when 0 E2E tests (computed)', () => {
    // Synthetic graph with NO e2e-level test → the System row must be ✗, not blank.
    const zeroE2e: Graph = {
      nodes: [
        { uid: 'SYS-x', type: 'SYS', name: 'X', attributes: {} },
        { uid: 'UC-x', type: 'UC', name: 'UC', attributes: {} },
        { uid: 'FUNC-x', type: 'FUNC', name: 'F', attributes: {} },
        {
          uid: 'TEST-x',
          type: 'TEST',
          name: 'unit',
          attributes: { testRef: { file: 'a.test.ts', tool: 'vitest', level: 'unit' } },
        },
      ],
      edges: [],
    };
    const md = exportMarkdown(zeroE2e, 'testconcept');
    expect(md).toContain('✗ MISSING');
    expect(md).toContain('NO end-to-end run exists');
    // The System row reports 0 E2E tests, loudly.
    expect(md).toMatch(/System \| SYS \(1\) \| E2E \| 0/);

    // And with an e2e test present, the same render flips to ✓ (computed both ways).
    const withE2e: Graph = {
      ...zeroE2e,
      nodes: [
        ...zeroE2e.nodes,
        {
          uid: 'TEST-e2e',
          type: 'TEST',
          name: 'e2e',
          attributes: { testRef: { file: 'e.test.ts', tool: 'vitest', level: 'e2e' } },
        },
      ],
    };
    const md2 = exportMarkdown(withE2e, 'testconcept');
    expect(md2).not.toContain('✗ MISSING');
    expect(md2).toMatch(/System \| SYS \(1\) \| E2E \| 1/);
  });

  it('CR-GC-220: FMEA/Trade render an explicit empty-state (never silently blank)', () => {
    // The live graph has no risk REQ / trade relations yet — must say so, not be empty.
    const fmea = exportMarkdown(graph, 'fmea');
    expect(fmea).toContain('FMEA');
    const trade = exportMarkdown(graph, 'trade');
    expect(trade).toContain('Trade Studies');
  });

  it('CR-GC-220: VIEW_FILENAMES covers every view exactly once', () => {
    for (const v of MARKDOWN_VIEWS) {
      expect(VIEW_FILENAMES[v]).toMatch(/\.md$/);
    }
    const files = MARKDOWN_VIEWS.map((v) => VIEW_FILENAMES[v]);
    expect(new Set(files).size).toBe(files.length); // no filename collision
  });
});
