/**
 * TEST-doc-export — Graph → JSON/Markdown re-exporter (CR-GC-113).
 *
 * Verifies the single SSOT sync path:
 *   1. ROUND-TRIP: import the committed SSOT JSON into a REAL disk Kuzu harness,
 *      pull the IN-MEMORY authoritative graph (harness.getGraph() — NOT a fresh
 *      Kuzu reload, which is lossy), exportGraphJson, assert BYTE-IDENTICAL to
 *      the committed file. Output is asserted in memory only — the repo SSOT is
 *      never written.
 *   2. DETERMINISM: exportGraphJson and exportMarkdown each produce byte-identical
 *      output across two calls.
 *   3. exportMarkdown emits the GENERATED header and is non-empty for every view.
 *
 * Real KuzuAdapter on a mkdtemp disk path — no mocks, never :memory:.
 */
import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { mkdtempSync, rmSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { KuzuAdapter } from '@sigloch/graph-cypher-wasm';
import { SE_DESCRIPTOR } from '@sigloch/graph-api-core';
import type { Graph } from '@sigloch/graph-api-core';
import { GraphCodeHarness } from '../src/harness.js';
import {
  exportGraphJson,
  exportMarkdown,
  MARKDOWN_VIEWS,
  MarkdownViewSchema,
} from '../src/exporter.js';
import type { HarnessConfig } from '@sigloch/contracts/harness';

const REPO_ROOT = join(__dirname, '..');
const GRAPH_JSON = join(REPO_ROOT, 'docs/graph/graphcode.graph.json');

function makeConfig(repoRoot: string): HarnessConfig {
  return {
    repoRoot,
    scope: { workspaceId: 'test-ws', systemId: 'graphcode' },
    consumerType: 'system',
    preCommitTimeout: 5000,
  };
}

describe('exportGraphJson / exportMarkdown (TEST-doc-export)', () => {
  let tmp: string;
  let harness: GraphCodeHarness;
  let graph: Graph;
  let committedRaw: string;

  beforeAll(async () => {
    committedRaw = readFileSync(GRAPH_JSON, 'utf8');
    tmp = mkdtempSync(join(tmpdir(), 'graphcode-export-'));
    const storage = new KuzuAdapter({ ontology: SE_DESCRIPTOR, path: join(tmp, 'kuzu') });
    harness = new GraphCodeHarness(makeConfig(REPO_ROOT), storage);
    await harness.initialize();
    // seedFromJson() loads the committed SSOT via importGraph and sets the
    // in-memory authoritative graph (full attribute fidelity). getGraph() returns
    // THAT working copy — not a lossy Kuzu reload.
    await harness.seedFromJson();
    graph = harness.getGraph();
  });

  afterAll(async () => {
    await harness.close();
    rmSync(tmp, { recursive: true, force: true });
  });

  it('ROUND-TRIP: exportGraphJson of the in-memory SSOT is byte-identical to the committed file', () => {
    const exported = exportGraphJson(graph);
    // Byte-identical: exporter is the exact inverse of importGraph and the
    // committed file is already in canonical `JSON.stringify(_, null, 2) + "\n"` form.
    expect(exported).toBe(committedRaw);
    expect(Buffer.from(exported).equals(Buffer.from(committedRaw))).toBe(true);
  });

  it('ROUND-TRIP preserves lossy-in-Kuzu attributes (status/kinds/method/nested attributes)', () => {
    const exported = JSON.parse(exportGraphJson(graph)) as {
      elements: Array<Record<string, unknown>>;
    };
    const byId = new Map(exported.elements.map((e) => [e.id as string, e]));
    // status — dropped on a raw Kuzu reload, present here.
    expect(byId.get('MOD-docs')?.status).toBeDefined();
    // kinds — REQ-only top-level attr.
    expect(byId.get('REQ-doc-export')?.kinds).toBeDefined();
    // method — TEST-only top-level attr.
    expect(byId.get('TEST-doc-export')?.method).toBeDefined();
    // nested `attributes` object (SCHEMA zodDefinition).
    const schema = byId.get('SCHEMA-mutate-command') as { attributes?: { zodDefinition?: string } };
    expect(schema?.attributes?.zodDefinition).toBeTypeOf('string');
  });

  it('DETERMINISM: exportGraphJson is byte-identical across two calls', () => {
    expect(exportGraphJson(graph)).toBe(exportGraphJson(graph));
  });

  it('DETERMINISM: exportMarkdown is byte-identical across two calls (every view)', () => {
    for (const view of MARKDOWN_VIEWS) {
      expect(exportMarkdown(graph, view)).toBe(exportMarkdown(graph, view));
    }
  });

  it('exportMarkdown emits the GENERATED header and is non-empty for every view', () => {
    for (const view of MARKDOWN_VIEWS) {
      const md = exportMarkdown(graph, view);
      expect(md.length).toBeGreaterThan(0);
      expect(md).toContain('GENERATED by @sigloch/graphcode exportMarkdown');
      expect(md).toContain('DO NOT HAND-EDIT');
      expect(md).toContain('docs/graph/graphcode.graph.json');
      // No `()` or `|` inside any rendered Mermaid label (we emit no Mermaid, so
      // assert there is no mermaid fence at all — keeps the blank-diagram hazard out).
      expect(md).not.toContain('```mermaid');
    }
  });

  it('the four supported views mirror FLOW-export-request (spec/architecture/cr-list/references)', () => {
    expect([...MARKDOWN_VIEWS].sort()).toEqual(
      ['architecture', 'cr-list', 'references', 'spec'].sort(),
    );
    // schema rejects unknown views.
    expect(() => MarkdownViewSchema.parse('bogus')).toThrow();
  });

  it('exportMarkdown reflects the graph: cr-list lists CR nodes, references lists traces', () => {
    const crList = exportMarkdown(graph, 'cr-list');
    const crCount = graph.nodes.filter((n) => n.type === 'CR').length;
    expect(crCount).toBeGreaterThan(0);
    // CR-GC-113 itself must appear in the CR view.
    expect(crList).toContain('CR-GC-113');

    const refs = exportMarkdown(graph, 'references');
    // A known trace from the graph appears in the references view.
    const firstEdge = graph.edges[0];
    expect(refs).toContain(firstEdge.sourceId);
    expect(refs).toContain(firstEdge.targetId);
  });
});
