/**
 * TEST-doc-export — Graph → JSON/Markdown re-exporter (CR-GC-113).
 *
 * Verifies the single SSOT sync path:
 *   1. ROUND-TRIP: import the committed SSOT JSON into a REAL disk Kuzu harness,
 *      pull the IN-MEMORY authoritative graph (harness.getGraph() — NOT a fresh
 *      Kuzu reload, which is lossy), exportGraphJson, assert BYTE-IDENTICAL to
 *      the committed file. Output is asserted in memory only — the repo SSOT is
 *      never written.
 *   2. DETERMINISM: exportGraphJson and exportMarkdown each produce byte-identical
 *      output across two calls.
 *   3. exportMarkdown emits the GENERATED header and is non-empty for every view.
 *
 * Real KuzuAdapter on a mkdtemp disk path — no mocks, never :memory:.
 */
import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { mkdtempSync, rmSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { KuzuAdapter } from '@sigloch/graph-cypher-wasm';
import { SE_DESCRIPTOR } from '@sigloch/graph-api-core';
import type { Graph } from '@sigloch/graph-api-core';
import { GraphCodeHarness } from '../src/harness.js';
import {
  exportGraphJson,
  exportMarkdown,
  MARKDOWN_VIEWS,
  MarkdownViewSchema,
  VIEW_FILENAMES,
} from '../src/exporter.js';
import type { HarnessConfig } from '@sigloch/contracts/harness';

const REPO_ROOT = join(__dirname, '..');
const GRAPH_JSON = join(REPO_ROOT, 'docs/graph/graphcode.graph.json');

function makeConfig(repoRoot: string): HarnessConfig {
  return {
    repoRoot,
    scope: { workspaceId: 'test-ws', systemId: 'graphcode' },
    consumerType: 'system',
    preCommitTimeout: 5000,
  };
}

describe('exportGraphJson / exportMarkdown (TEST-doc-export)', () => {
  let tmp: string;
  let harness: GraphCodeHarness;
  let graph: Graph;
  let committedRaw: string;

  beforeAll(async () => {
    committedRaw = readFileSync(GRAPH_JSON, 'utf8');
    tmp = mkdtempSync(join(tmpdir(), 'graphcode-export-'));
    const storage = new KuzuAdapter({ ontology: SE_DESCRIPTOR, path: join(tmp, 'kuzu') });
    // lockDir = temp store dir, not repoRoot/.graphcode (a live dev server owns that, CR-GC-218).
    harness = new GraphCodeHarness(makeConfig(REPO_ROOT), storage, undefined, { lockDir: tmp });
    await harness.initialize();
    // seedFromJson() loads the committed SSOT via importGraph and sets the
    // in-memory authoritative graph (full attribute fidelity). getGraph() returns
    // THAT working copy — not a lossy Kuzu reload.
    await harness.seedFromJson();
    graph = harness.getGraph();
  });

  afterAll(async () => {
    await harness.close();
    rmSync(tmp, { recursive: true, force: true });
  });

  it('ROUND-TRIP: exportGraphJson of the in-memory SSOT is byte-identical to the committed file', () => {
    const exported = exportGraphJson(graph);
    // Byte-identical: exporter is the exact inverse of importGraph and the
    // committed file is already in canonical `JSON.stringify(_, null, 2) + "\n"` form.
    expect(exported).toBe(committedRaw);
    expect(Buffer.from(exported).equals(Buffer.from(committedRaw))).toBe(true);
  });

  it('ROUND-TRIP preserves lossy-in-Kuzu attributes (status/kinds/method/nested attributes)', () => {
    const exported = JSON.parse(exportGraphJson(graph)) as {
      elements: Array<Record<string, unknown>>;
    };
    const byId = new Map(exported.elements.map((e) => [e.id as string, e]));
    // status — dropped on a raw Kuzu reload, present here.
    expect(byId.get('MOD-docs')?.status).toBeDefined();
    // kinds — REQ-only top-level attr.
    expect(byId.get('REQ-doc-export')?.kinds).toBeDefined();
    // method — TEST-only top-level attr.
    expect(byId.get('TEST-doc-export')?.method).toBeDefined();
    // operatingMode — FLATTENED to a top-level attribute (CR-GC-219): the old nested
    // `attributes.operatingMode` artifact is gone; the value is preserved one level up.
    const func = byId.get('FUNC-export-markdown') as { attributes?: unknown; operatingMode?: unknown };
    expect(func?.operatingMode).toBeTypeOf('string');
    expect(func?.attributes).toBeUndefined();
  });

  it('DETERMINISM: exportGraphJson is byte-identical across two calls', () => {
    expect(exportGraphJson(graph)).toBe(exportGraphJson(graph));
  });

  it('DETERMINISM: exportMarkdown is byte-identical across two calls (every view)', () => {
    for (const view of MARKDOWN_VIEWS) {
      expect(exportMarkdown(graph, view)).toBe(exportMarkdown(graph, view));
    }
  });

  it('exportMarkdown emits the GENERATED header and is non-empty for every view', () => {
    for (const view of MARKDOWN_VIEWS) {
      const md = exportMarkdown(graph, view);
      expect(md.length).toBeGreaterThan(0);
      expect(md).toContain('GENERATED by @sigloch/graphcode exportMarkdown');
      expect(md).toContain('DO NOT HAND-EDIT');
      expect(md).toContain('docs/graph/graphcode.graph.json');
      // No `()` or `|` inside any rendered Mermaid label (we emit no Mermaid, so
      // assert there is no mermaid fence at all — keeps the blank-diagram hazard out).
      expect(md).not.toContain('```mermaid');
    }
  });

  // -------------------------------------------------------------------------
  // CR-GC-236 — header follows the export/member name, no hardcoded 'graphcode'.
  // -------------------------------------------------------------------------

  it('CR-GC-236: exportMarkdown(name) puts the member name in title + SSOT path (every view)', () => {
    for (const view of MARKDOWN_VIEWS) {
      const md = exportMarkdown(graph, view, 'graph-view-edit');
      expect(md).toContain('# graph-view-edit — ');
      expect(md).toContain('Source of truth: docs/graph/graph-view-edit.graph.json');
      expect(md).toContain('GENERATED from `docs/graph/graph-view-edit.graph.json`');
      // The GENERATED header must not claim graphcode's SSOT (node descriptions
      // in the body may legitimately mention the file name).
      const header = md.split('\n').slice(0, 8).join('\n');
      expect(header).not.toContain('graphcode.graph.json');
    }
  });

  it('CR-GC-236: default name is graphcode (own export keeps its SSOT path)', () => {
    const md = exportMarkdown(graph, 'spec');
    expect(md).toContain('# graphcode — ');
    expect(md).toContain('docs/graph/graphcode.graph.json');
  });

  it('CR-GC-236: DETERMINISM — same graph + same name → identical bytes', () => {
    for (const view of MARKDOWN_VIEWS) {
      expect(exportMarkdown(graph, view, 'member-x')).toBe(exportMarkdown(graph, view, 'member-x'));
    }
  });

  it('the foundation views mirror FLOW-export-request (spec/architecture/cr-list/references)', () => {
    // The four foundation views are still present (CR-GC-220 ADDS to them, no parallel path).
    for (const v of ['architecture', 'cr-list', 'references', 'spec']) {
      expect([...MARKDOWN_VIEWS]).toContain(v);
    }
    // schema rejects unknown views.
    expect(() => MarkdownViewSchema.parse('bogus')).toThrow();
  });

  it('exportMarkdown reflects the graph: cr-list lists CR nodes, references lists traces', () => {
    const crList = exportMarkdown(graph, 'cr-list');
    const crCount = graph.nodes.filter((n) => n.type === 'CR').length;
    expect(crCount).toBeGreaterThan(0);
    // CR-GC-113 itself must appear in the CR view.
    expect(crList).toContain('CR-GC-113');

    const refs = exportMarkdown(graph, 'references');
    // A known trace from the graph appears in the references view.
    const firstEdge = graph.edges[0];
    expect(refs).toContain(firstEdge.sourceId);
    expect(refs).toContain(firstEdge.targetId);
  });

  // -------------------------------------------------------------------------
  // CR-GC-220 — the 12 deterministic SE-artifact render views.
  // -------------------------------------------------------------------------

  const CR220_VIEWS = [
    'srs',
    'nfr',
    'rtm',
    'icd',
    'testconcept',
    'testmatrix',
    'intplan',
    'changelog',
    'fmea',
    'conops',
    'trade',
    'implplan',
  ] as const;

  it('CR-GC-220: schema accepts all 12 new views plus spec (16 total)', () => {
    for (const v of CR220_VIEWS) expect(() => MarkdownViewSchema.parse(v)).not.toThrow();
    expect(MARKDOWN_VIEWS.length).toBe(16);
    expect([...MARKDOWN_VIEWS]).toContain('spec'); // full dump kept
  });

  it('CR-GC-220: every new view renders non-empty with the GENERATED header', () => {
    for (const v of CR220_VIEWS) {
      const md = exportMarkdown(graph, v);
      expect(md.length).toBeGreaterThan(0);
      expect(md).toContain('GENERATED by @sigloch/graphcode exportMarkdown');
      expect(md).toContain('DO NOT HAND-EDIT');
      expect(md).not.toContain('```mermaid');
    }
  });

  it('CR-GC-220: every new view is byte-identical across two renders (determinism)', () => {
    for (const v of CR220_VIEWS) {
      const a = exportMarkdown(graph, v);
      const b = exportMarkdown(graph, v);
      expect(Buffer.from(a).equals(Buffer.from(b))).toBe(true);
    }
  });

  it('CR-GC-220: SRS (textual spec) ≠ model spec (full dump)', () => {
    const srs = exportMarkdown(graph, 'srs');
    const spec = exportMarkdown(graph, 'spec');
    expect(srs).not.toBe(spec);
    // SRS carries the specification scaffolding; spec is a type-grouped dump.
    expect(srs).toContain('System Requirements Specification');
    expect(srs).toContain('## 3  Use Cases & Verhalten');
    expect(spec).toContain('Modell-Spezifikation');
    expect(spec).not.toContain('System Requirements Specification');
    // SRS renders elements as per-uid headings, not the dump's type sections.
    expect(spec).toContain('## FUNC');
    expect(srs).not.toContain('## FUNC');
  });

  // -------------------------------------------------------------------------
  // CR-GVE-172 — SRS as a full textual spec (aise text-view pattern).
  // -------------------------------------------------------------------------

  it('CR-GVE-172: SRS places each REQ under its satisfy element, repeats multi-satisfier occurrences', () => {
    const g: Graph = {
      nodes: [
        { uid: 'SYS-x', type: 'SYS', name: 'X', description: 'the system', attributes: {} },
        { uid: 'ACTOR-a', type: 'ACTOR', name: 'A', description: 'actor', attributes: {} },
        { uid: 'UC-u', type: 'UC', name: 'U', description: 'use case', attributes: {} },
        { uid: 'FCHAIN-c', type: 'FCHAIN', name: 'C', description: 'chain', attributes: {} },
        { uid: 'FUNC-first', type: 'FUNC', name: 'First', description: 'f1', attributes: {} },
        { uid: 'FUNC-second', type: 'FUNC', name: 'Second', description: 'f2', attributes: {} },
        { uid: 'FLOW-f', type: 'FLOW', name: 'F', description: 'flow', attributes: {} },
        { uid: 'SCHEMA-s', type: 'SCHEMA', name: 'S', description: 'schema', attributes: {} },
        { uid: 'MOD-m', type: 'MOD', name: 'M', description: 'module', attributes: {} },
        { uid: 'REQ-shared', type: 'REQ', name: 'shared', description: 'satisfied twice', attributes: {} },
        { uid: 'REQ-orphan', type: 'REQ', name: 'orphan', description: 'no satisfier', attributes: {} },
        { uid: 'TEST-t', type: 'TEST', name: 'T', description: 'test', attributes: {} },
      ],
      edges: [
        { sourceId: 'SYS-x', targetId: 'UC-u', edgeType: 'compose', attributes: {} },
        { sourceId: 'UC-u', targetId: 'FCHAIN-c', edgeType: 'compose', attributes: {} },
        { sourceId: 'FCHAIN-c', targetId: 'FUNC-first', edgeType: 'compose', attributes: {} },
        { sourceId: 'FCHAIN-c', targetId: 'FUNC-second', edgeType: 'compose', attributes: {} },
        // io chain runs Second-less uid AFTER First: FUNC-first → FLOW-f → FUNC-second.
        { sourceId: 'FUNC-first', targetId: 'FLOW-f', edgeType: 'io', attributes: {} },
        { sourceId: 'FLOW-f', targetId: 'FUNC-second', edgeType: 'io', attributes: {} },
        { sourceId: 'ACTOR-a', targetId: 'UC-u', edgeType: 'io', attributes: {} },
        { sourceId: 'FLOW-f', targetId: 'SCHEMA-s', edgeType: 'relation', attributes: {} },
        { sourceId: 'FUNC-second', targetId: 'REQ-shared', edgeType: 'satisfy', attributes: {} },
        { sourceId: 'FCHAIN-c', targetId: 'REQ-shared', edgeType: 'satisfy', attributes: {} },
        { sourceId: 'MOD-m', targetId: 'REQ-shared', edgeType: 'satisfy', attributes: {} },
        { sourceId: 'FUNC-second', targetId: 'MOD-m', edgeType: 'allocate', attributes: {} },
        { sourceId: 'TEST-t', targetId: 'REQ-shared', edgeType: 'verify', attributes: {} },
      ],
    };
    const srs = exportMarkdown(g, 'srs', 'test');

    // Every ontology type with instances appears (SESSION/CR/MS excluded by design).
    for (const uid of ['SYS-x', 'ACTOR-a', 'UC-u', 'FCHAIN-c', 'FUNC-first', 'FUNC-second', 'FLOW-f', 'SCHEMA-s', 'MOD-m', 'REQ-shared', 'REQ-orphan', 'TEST-t']) {
      expect(srs).toContain(uid);
    }

    // io-topological order: FUNC-first HEADING precedes FUNC-second's (plain
    // indexOf would hit `FUNC-second` in REQ-shared's trace line first).
    expect(srs.indexOf('`FUNC-first` —')).toBeLessThan(srs.indexOf('`FUNC-second` —'));

    // Durchgezogene Dezimal-Nummerierung bis zur vorletzten Ebene; REQ-Einträge
    // (unterste Ebene) bleiben unnummeriert.
    expect(srs).toContain('### 2.1  `ACTOR-a`');
    expect(srs).toContain('### 3.1  `UC-u`');
    expect(srs).toContain('#### 3.1.1  `FCHAIN-c`');
    expect(srs).toContain('##### 3.1.1.1  `FUNC-first`');
    expect(srs).toContain('##### 3.1.1.2  `FUNC-second`');
    expect(srs).toContain('### 5.1  `SCHEMA-s`'); // SCHEMA = eigenes Kapitel
    expect(srs).toContain('### 6.1  `MOD-m`');
    expect(srs).toMatch(/#{3,6} `REQ-shared`/); // unnummeriert

    // REQ-shared appears under BOTH rendered satisfiers (FCHAIN + FUNC) with the
    // cross-note; the architecture chapter carries NO REQ entries (satisfy ▶ line
    // on the MOD instead), and the orphan lands in cross-cutting.
    const first = srs.indexOf('`REQ-shared`');
    const second = srs.indexOf('`REQ-shared`', first + 1);
    expect(first).toBeGreaterThan(-1);
    expect(second).toBeGreaterThan(first);
    expect(srs).toContain('auch unter');
    const arch = srs.slice(srs.indexOf('## 6  Architektur'), srs.indexOf('## 7  Cross-cutting'));
    expect(arch).not.toMatch(/#{3,6} `REQ-/); // kein REQ-Eintrag in der Architektur
    expect(arch).toContain('satisfy ▶ `REQ-shared`'); // aber als Trace-Zeile am MOD
    expect(srs.indexOf('`REQ-orphan`')).toBeGreaterThan(srs.indexOf('## 7  Cross-cutting'));
  });

  it('CR-GVE-172: io order wins over uid order within a FCHAIN', () => {
    // uid order would render FUNC-alpha first; the io chain runs beta → alpha.
    const g: Graph = {
      nodes: [
        { uid: 'SYS-x', type: 'SYS', name: 'X', attributes: {} },
        { uid: 'UC-u', type: 'UC', name: 'U', attributes: {} },
        { uid: 'FCHAIN-c', type: 'FCHAIN', name: 'C', attributes: {} },
        { uid: 'FUNC-alpha', type: 'FUNC', name: 'Alpha', attributes: {} },
        { uid: 'FUNC-beta', type: 'FUNC', name: 'Beta', attributes: {} },
        { uid: 'FLOW-f', type: 'FLOW', name: 'F', attributes: {} },
      ],
      edges: [
        { sourceId: 'UC-u', targetId: 'FCHAIN-c', edgeType: 'compose', attributes: {} },
        { sourceId: 'FCHAIN-c', targetId: 'FUNC-alpha', edgeType: 'compose', attributes: {} },
        { sourceId: 'FCHAIN-c', targetId: 'FUNC-beta', edgeType: 'compose', attributes: {} },
        { sourceId: 'FUNC-beta', targetId: 'FLOW-f', edgeType: 'io', attributes: {} },
        { sourceId: 'FLOW-f', targetId: 'FUNC-alpha', edgeType: 'io', attributes: {} },
      ],
    };
    const srs = exportMarkdown(g, 'srs', 'test');
    expect(srs.indexOf('`FUNC-beta`')).toBeLessThan(srs.indexOf('`FUNC-alpha`'));
  });

  it('CR-GC-220: NFR view only lists non-functional REQ', () => {
    const nfr = exportMarkdown(graph, 'nfr');
    const nonFunc = graph.nodes.filter(
      (n) => n.type === 'REQ' && Array.isArray(n.attributes['kinds']) &&
        (n.attributes['kinds'] as string[]).includes('non-functional'),
    );
    expect(nonFunc.length).toBeGreaterThan(0);
    expect(nfr).toContain(nonFunc[0].uid);
    // A purely functional REQ (kinds without non-functional) must NOT appear.
    const func = graph.nodes.find(
      (n) => n.type === 'REQ' && Array.isArray(n.attributes['kinds']) &&
        (n.attributes['kinds'] as string[]).includes('functional') &&
        !(n.attributes['kinds'] as string[]).includes('non-functional'),
    );
    if (func) expect(nfr).not.toContain(func.uid);
  });

  it('CR-GC-220/240: TestConcept shows System E2E as ✗ MISSING when 0 E2E-level tests exist (level from graph position)', () => {
    // A FUNC-satisfied REQ verified by a test, but no REQ composed by SYS at
    // all → the System row must be ✗, not blank. No testRef.level anywhere.
    const zeroE2e: Graph = {
      nodes: [
        { uid: 'SYS-x', type: 'SYS', name: 'X', attributes: {} },
        { uid: 'UC-x', type: 'UC', name: 'UC', attributes: {} },
        { uid: 'FUNC-x', type: 'FUNC', name: 'F', attributes: {} },
        { uid: 'REQ-func', type: 'REQ', name: 'r', attributes: {} },
        { uid: 'TEST-unit', type: 'TEST', name: 'unit', attributes: {} },
      ],
      edges: [
        { sourceId: 'FUNC-x', targetId: 'REQ-func', edgeType: 'satisfy', attributes: {} },
        { sourceId: 'TEST-unit', targetId: 'REQ-func', edgeType: 'verify', attributes: {} },
      ],
    };
    const md = exportMarkdown(zeroE2e, 'testconcept');
    expect(md).toContain('✗ MISSING');
    expect(md).toContain('NO end-to-end run exists');
    // The System row reports 0 E2E tests, loudly.
    expect(md).toMatch(/System \| SYS \(1\) \| E2E \| 0/);

    // Adding a SYS-composed REQ verified by a test flips the row to ✓ — purely
    // via graph position (CR-GC-240), still no testRef.level anywhere.
    const withE2e: Graph = {
      nodes: [
        ...zeroE2e.nodes,
        { uid: 'REQ-sys', type: 'REQ', name: 'r2', attributes: {} },
        { uid: 'TEST-e2e', type: 'TEST', name: 'e2e', attributes: {} },
      ],
      edges: [
        ...zeroE2e.edges,
        { sourceId: 'SYS-x', targetId: 'REQ-sys', edgeType: 'compose', attributes: {} },
        { sourceId: 'TEST-e2e', targetId: 'REQ-sys', edgeType: 'verify', attributes: {} },
      ],
    };
    const md2 = exportMarkdown(withE2e, 'testconcept');
    expect(md2).not.toContain('✗ MISSING');
    expect(md2).toMatch(/System \| SYS \(1\) \| E2E \| 1/);
  });

  it('CR-GC-240: full REQ coverage renders a clean pyramid with ZERO testRef.level attributes anywhere', () => {
    // 1 SYS, 2 UC, 1 FUNC — every REQ verified, no TEST carries testRef/level.
    // Before CR-GC-240 this degenerated to e2e=integration=unit=0 (attribute-based).
    const graph: Graph = {
      nodes: [
        { uid: 'SYS-p', type: 'SYS', name: 'sys', attributes: {} },
        { uid: 'UC-1', type: 'UC', name: 'uc1', attributes: {} },
        { uid: 'UC-2', type: 'UC', name: 'uc2', attributes: {} },
        { uid: 'FUNC-p', type: 'FUNC', name: 'func', attributes: {} },
        { uid: 'REQ-sys', type: 'REQ', name: 'sys req', attributes: {} },
        { uid: 'REQ-uc1', type: 'REQ', name: 'uc1 req', attributes: {} },
        { uid: 'REQ-uc2', type: 'REQ', name: 'uc2 req', attributes: {} },
        { uid: 'REQ-func', type: 'REQ', name: 'func req', attributes: {} },
        { uid: 'TEST-sys', type: 'TEST', name: 't-sys', attributes: {} },
        { uid: 'TEST-uc1', type: 'TEST', name: 't-uc1', attributes: {} },
        { uid: 'TEST-uc2', type: 'TEST', name: 't-uc2', attributes: {} },
        { uid: 'TEST-func', type: 'TEST', name: 't-func', attributes: {} },
      ],
      edges: [
        { sourceId: 'SYS-p', targetId: 'REQ-sys', edgeType: 'compose', attributes: {} },
        { sourceId: 'UC-1', targetId: 'REQ-uc1', edgeType: 'compose', attributes: {} },
        { sourceId: 'UC-2', targetId: 'REQ-uc2', edgeType: 'compose', attributes: {} },
        { sourceId: 'FUNC-p', targetId: 'REQ-func', edgeType: 'satisfy', attributes: {} },
        { sourceId: 'TEST-sys', targetId: 'REQ-sys', edgeType: 'verify', attributes: {} },
        { sourceId: 'TEST-uc1', targetId: 'REQ-uc1', edgeType: 'verify', attributes: {} },
        { sourceId: 'TEST-uc2', targetId: 'REQ-uc2', edgeType: 'verify', attributes: {} },
        { sourceId: 'TEST-func', targetId: 'REQ-func', edgeType: 'verify', attributes: {} },
      ],
    };
    const md = exportMarkdown(graph, 'testconcept');
    expect(md).not.toContain('✗ MISSING');
    expect(md).not.toContain('GAP');
    expect(md).not.toContain('UC have no scenario path');
    expect(md).toMatch(/System \| SYS \(1\) \| E2E \| 1 \| 1 \/ 1 \| ✓/);
    expect(md).toMatch(/Use-case \| UC \(2\) \| acceptance \/ integration \| 2 \| 2 \/ 2 scenario \| ✓/);
    expect(md).toMatch(/Function \| FUNC \(1\) \| unit \| 1 \| 1 \/ 1 \| ✓/);
  });

  it('R-21: TestConcept flags a FUNC↔FUNC connection with no integration test as ✗ GAP', () => {
    // FUNC-a ─io→ FLOW-x ─io→ FUNC-b, both in FCHAIN-c, but the chain REQ is unverified.
    const uncovered: Graph = {
      nodes: [
        { uid: 'FUNC-a', type: 'FUNC', name: 'a', attributes: {} },
        { uid: 'FUNC-b', type: 'FUNC', name: 'b', attributes: {} },
        { uid: 'FLOW-x', type: 'FLOW', name: 'x', attributes: {} },
        { uid: 'FCHAIN-c', type: 'FCHAIN', name: 'c', attributes: {} },
        { uid: 'REQ-int', type: 'REQ', name: 'int req', attributes: {} },
      ],
      edges: [
        { sourceId: 'FUNC-a', targetId: 'FLOW-x', edgeType: 'io', attributes: {} },
        { sourceId: 'FLOW-x', targetId: 'FUNC-b', edgeType: 'io', attributes: {} },
        { sourceId: 'FCHAIN-c', targetId: 'FUNC-a', edgeType: 'compose', attributes: {} },
        { sourceId: 'FCHAIN-c', targetId: 'FUNC-b', edgeType: 'compose', attributes: {} },
        { sourceId: 'FCHAIN-c', targetId: 'REQ-int', edgeType: 'satisfy', attributes: {} },
      ],
    };
    const md = exportMarkdown(uncovered, 'testconcept');
    // FUNC↔FUNC integration sits in the integration band — ABOVE the unit row.
    expect(md.indexOf('| Integration | FUNC↔FUNC')).toBeLessThan(md.indexOf('| Function |'));
    expect(md.indexOf('| Integration | FUNC↔FUNC')).toBeGreaterThan(md.indexOf('| Use-case |'));
    expect(md).toContain('0/1 FUNC↔FUNC connections tested  ← GAP');
    expect(md).toMatch(/Integration \| FUNC↔FUNC \(1 conn\) \| integration \(chain\) \| \d+ \| 0 \/ 1 connections \| ✗ 1 uncovered/);

    // Add the verifying integration test → connection covered, integration level counted.
    const covered: Graph = {
      nodes: [...uncovered.nodes, { uid: 'TEST-int', type: 'TEST', name: 't-int', attributes: {} }],
      edges: [...uncovered.edges, { sourceId: 'TEST-int', targetId: 'REQ-int', edgeType: 'verify', attributes: {} }],
    };
    const md2 = exportMarkdown(covered, 'testconcept');
    expect(md2).toContain('✓ 1/1 FUNC↔FUNC connections integration-tested');
    expect(md2).not.toContain('FUNC↔FUNC connections tested  ← GAP');
    // FCHAIN-satisfied REQ verified → the test counts as integration level.
    expect(md2).toMatch(/Integration \| FUNC↔FUNC \(1 conn\) \| integration \(chain\) \| 1 \| 1 \/ 1 connections \| ✓/);
  });

  it('CR-GC-220: FMEA/Trade render an explicit empty-state (never silently blank)', () => {
    // The live graph has no risk REQ / trade relations yet — must say so, not be empty.
    const fmea = exportMarkdown(graph, 'fmea');
    expect(fmea).toContain('FMEA');
    const trade = exportMarkdown(graph, 'trade');
    expect(trade).toContain('Trade Studies');
  });

  it('CR-GC-220: VIEW_FILENAMES covers every view exactly once', () => {
    for (const v of MARKDOWN_VIEWS) {
      expect(VIEW_FILENAMES[v]).toMatch(/\.md$/);
    }
    const files = MARKDOWN_VIEWS.map((v) => VIEW_FILENAMES[v]);
    expect(new Set(files).size).toBe(files.length); // no filename collision
  });
});
