/**
 * Graph → Markdown/JSON Re-Exporter (CR-GC-113, MOD-docs).
 *
 * The single SSOT sync path: render the live graph back into commit-able docs.
 * Realizes FUNC-export-markdown / REQ-doc-export / REQ-pre-export-markdown /
 * REQ-post-export-markdown / FUNC-render-views; SCHEMA-markdown-view is the
 * MarkdownView schema below.
 *
 * EXPORT SOURCE = the harness IN-MEMORY authoritative working copy
 * (`harness.getGraph()`), NOT a fresh Kuzu reload.
 *   Kuzu is the durable QUERY INDEX, but its storage is LOSSY for arbitrary
 *   attributes — KuzuAdapter only persists declared property columns
 *   (name/description + declared props), so a raw Kuzu reload drops
 *   status/kinds/method/nested-`attributes`/etc. The full-fidelity graph is the
 *   JSON loaded by `importGraph()` and updated by the gate on every `mutate()`.
 *   Full-attribute Kuzu persistence is a known follow-up.
 *
 * `exportGraphJson` is the exact INVERSE of `GraphCodeHarness.importGraph`:
 *   element = { id: node.uid, type, name, description, ...node.attributes }
 *   trace   = { source: edge.sourceId, target: edge.targetId, type: edge.edgeType, ...edge.attributes }
 * Serialized canonically as `JSON.stringify(obj, null, 2) + "\n"` — the canonical
 * form the graph-integrity safety-net asserts, and byte-identical across calls.
 *
 * @author andreas@siglochconsulting
 */
import { z } from 'zod/v4';
import type { Graph, GraphNode, GraphEdge } from '@sigloch/graph-api-core';
import { TestRefSchema, type TestRef } from '@sigloch/contracts/se';

// ---------------------------------------------------------------------------
// SCHEMA-markdown-view — app-specific, NOT in @sigloch/contracts.
// ---------------------------------------------------------------------------

/**
 * MarkdownView (SCHEMA-markdown-view): which generated, human-readable view to
 * render. View names mirror FLOW-export-request (spec/architecture/cr-list/
 * references); each renders deterministically with a GENERATED header.
 */
export const MarkdownViewSchema = z.enum(['spec', 'architecture', 'cr-list', 'references']);
export type MarkdownView = z.infer<typeof MarkdownViewSchema>;

/** All supported views, in deterministic order. */
export const MARKDOWN_VIEWS: readonly MarkdownView[] = MarkdownViewSchema.options;

// ---------------------------------------------------------------------------
// exportGraphJson — inverse of importGraph, canonical serialization.
// ---------------------------------------------------------------------------

/** Element shape in the materialized OntologyGraph JSON (`id` first, attrs spread). */
function nodeToElement(node: GraphNode): Record<string, unknown> {
  return {
    id: node.uid,
    type: node.type,
    name: node.name,
    description: node.description ?? '',
    // Spread attributes back to top-level, preserving their insertion order so
    // status/created_at/updated_at/kinds/method/nested-attributes land exactly
    // where importGraph put them. Inverse of `{ id, type, name, description, ...rest }`.
    ...node.attributes,
  };
}

/** Trace shape in the materialized OntologyGraph JSON. */
function edgeToTrace(edge: GraphEdge): Record<string, unknown> {
  return {
    source: edge.sourceId,
    target: edge.targetId,
    type: edge.edgeType,
    ...edge.attributes,
  };
}

/**
 * Reconstruct the committed JSON shape `{ elements, traces }` from a Graph and
 * serialize CANONICALLY (`JSON.stringify(obj, null, 2) + "\n"`).
 *
 * DETERMINISTIC and SOURCE-ORDER-INDEPENDENT (REQ-deterministic-serialization R3):
 * elements are sorted by uid, traces by (source, type, target). Attribute key
 * order is preserved by importGraph / the Kuzu `attrs_json` round-trip. This makes
 * the export byte-identical whether the graph came from the committed JSON, the
 * gate's in-memory array, or a reload from the Kuzu SSOT — the precondition for
 * CR-GC-201's provenance check (committed JSON == export(store)).
 */
export function exportGraphJson(graph: Graph): string {
  const elements = [...graph.nodes]
    .sort((a, b) => a.uid.localeCompare(b.uid))
    .map(nodeToElement);
  const traces = [...graph.edges]
    .sort(
      (a, b) =>
        a.sourceId.localeCompare(b.sourceId) ||
        a.edgeType.localeCompare(b.edgeType) ||
        a.targetId.localeCompare(b.targetId),
    )
    .map(edgeToTrace);
  return JSON.stringify({ elements, traces }, null, 2) + '\n';
}

// ---------------------------------------------------------------------------
// exportMarkdown — deterministic views with a GENERATED header.
// ---------------------------------------------------------------------------

/** Marks a file as machine-generated; do-not-hand-edit. Stable across calls. */
function generatedHeader(title: string, subtitle: string): string {
  return [
    `<!-- GENERATED by @sigloch/graphcode exportMarkdown — DO NOT HAND-EDIT.`,
    `     Source of truth: docs/graph/graphcode.graph.json (the live graph).`,
    `     Re-render on model change: node scripts/export-graph.mjs -->`,
    ``,
    `# ${title}`,
    ``,
    `> GENERATED from \`docs/graph/graphcode.graph.json\` (SSOT). ${subtitle}`,
    ``,
  ].join('\n');
}

/** Stable lexicographic comparator on uid. */
function byUid(a: GraphNode, b: GraphNode): number {
  return a.uid.localeCompare(b.uid);
}

/** Stable comparator on [type, uid] for grouped listings. */
function byTypeThenUid(a: GraphNode, b: GraphNode): number {
  return a.type.localeCompare(b.type) || a.uid.localeCompare(b.uid);
}

/** A single-line, table-safe rendering of a description (no newlines / pipes). */
function cell(text: string): string {
  return (text ?? '').replace(/\s*\n\s*/g, ' ').replace(/\|/g, '/').trim();
}

function nodesOfTypes(graph: Graph, types: string[]): GraphNode[] {
  const set = new Set(types);
  return graph.nodes.filter((n) => set.has(n.type)).sort(byUid);
}

/** Overview/index of every element grouped by type (the `spec` view). */
function renderSpec(graph: Graph): string {
  const header = generatedHeader(
    'GraphCode — Modell-Spezifikation',
    'Alle Elemente nach Typ, sortiert nach uid. Deterministisch generiert.',
  );
  const sorted = [...graph.nodes].sort(byTypeThenUid);
  const lines: string[] = [header];
  lines.push(`Elemente: ${graph.nodes.length} · Traces: ${graph.edges.length}`, '');

  let currentType = '';
  for (const n of sorted) {
    if (n.type !== currentType) {
      currentType = n.type;
      lines.push('', `## ${currentType}`, '', '| uid | name | status | description |', '|---|---|---|---|');
    }
    const status = String(n.attributes['status'] ?? '');
    lines.push(`| \`${n.uid}\` | ${cell(n.name)} | ${status} | ${cell(n.description ?? '')} |`);
  }
  lines.push('');
  return lines.join('\n');
}

/** Module / function / system structure with allocate edges (the `architecture` view). */
function renderArchitecture(graph: Graph): string {
  const header = generatedHeader(
    'GraphCode — Architektur',
    'SYS / MOD / FUNC mit allocate-Zuordnung. Deterministisch generiert.',
  );
  const lines: string[] = [header];

  const structural = nodesOfTypes(graph, ['SYS', 'MOD', 'FUNC']);
  lines.push('## Strukturknoten', '', '| uid | type | name |', '|---|---|---|');
  for (const n of structural) {
    lines.push(`| \`${n.uid}\` | ${n.type} | ${cell(n.name)} |`);
  }
  lines.push('');

  // FUNC -allocate-> MOD assignment, sorted deterministically.
  const allocations = graph.edges
    .filter((e) => e.edgeType === 'allocate')
    .map((e) => ({ s: e.sourceId, t: e.targetId }))
    .sort((a, b) => a.s.localeCompare(b.s) || a.t.localeCompare(b.t));
  lines.push('## Allokation (FUNC -allocate-> MOD)', '', '| function | module |', '|---|---|');
  for (const a of allocations) {
    lines.push(`| \`${a.s}\` | \`${a.t}\` |`);
  }
  lines.push('');
  return lines.join('\n');
}

/** CR list (the `cr-list` view): every CR node with status. */
function renderCrList(graph: Graph): string {
  const header = generatedHeader(
    'GraphCode — Change-Requests',
    'Alle CR-Knoten, sortiert nach uid. Deterministisch generiert.',
  );
  const crs = nodesOfTypes(graph, ['CR']);
  const lines: string[] = [header];
  lines.push('| uid | name | status | description |', '|---|---|---|---|');
  for (const n of crs) {
    const status = String(n.attributes['status'] ?? '');
    lines.push(`| \`${n.uid}\` | ${cell(n.name)} | ${status} | ${cell(n.description ?? '')} |`);
  }
  lines.push('');
  return lines.join('\n');
}

/** Traceability references (the `references` view): every trace, sorted. */
function renderReferences(graph: Graph): string {
  const header = generatedHeader(
    'GraphCode — Traceability-References',
    'Alle Traces (source -type-> target), deterministisch sortiert.',
  );
  const traces = [...graph.edges]
    .map((e) => ({ s: e.sourceId, t: e.targetId, ty: e.edgeType }))
    .sort((a, b) => a.s.localeCompare(b.s) || a.ty.localeCompare(b.ty) || a.t.localeCompare(b.t));
  const lines: string[] = [header];
  lines.push('| source | type | target |', '|---|---|---|');
  for (const e of traces) {
    lines.push(`| \`${e.s}\` | ${e.ty} | \`${e.t}\` |`);
  }
  lines.push('');
  return lines.join('\n');
}

/**
 * Render a deterministic Markdown view of the graph with a GENERATED header.
 * Same (graph, view) → byte-identical output. Ordering is by uid / type / trace
 * key only (no insertion-order dependence). Renders no Mermaid, so the `()`/`|`
 * blank-diagram hazard does not apply; table cells are sanitized regardless.
 */
export function exportMarkdown(graph: Graph, view: MarkdownView): string {
  const v = MarkdownViewSchema.parse(view);
  switch (v) {
    case 'spec':
      return renderSpec(graph);
    case 'architecture':
      return renderArchitecture(graph);
    case 'cr-list':
      return renderCrList(graph);
    case 'references':
      return renderReferences(graph);
  }
}

/** Default file name for each view (under docs/views/). */
export const VIEW_FILENAMES: Record<MarkdownView, string> = {
  spec: 'spec.md',
  architecture: 'architecture.md',
  'cr-list': 'cr-list.md',
  references: 'references.md',
};

// ---------------------------------------------------------------------------
// Test-stub materialization (CR-GC-205 Item 4) — spec-time scaffolding so a TEST
// testRef NEVER resolves to a phantom file. A TEST can be bound to a file before
// it is implemented; rendering a minimal `it.todo` stub guarantees the file
// exists (graph_tests → real selective run, no false-green) while vitest reports
// the stub pending (suite stays green). Concept-only TESTs (no run artifact yet)
// are skipped. PURE — returns {file, content} for every bound TEST; the caller
// (graph_export) writes only files that don't already exist and NEVER overwrites.
// ---------------------------------------------------------------------------

/** A runnable stub the export would scaffold for one graph TEST binding. */
export interface TestStub {
  file: string;
  content: string;
}

export function renderTestStubs(graph: Graph): TestStub[] {
  const verifiesByTest = new Map<string, string[]>();
  for (const e of graph.edges) {
    if (e.edgeType !== 'verify') continue;
    const arr = verifiesByTest.get(e.sourceId) ?? [];
    arr.push(e.targetId);
    verifiesByTest.set(e.sourceId, arr);
  }
  const stubs: TestStub[] = [];
  for (const node of graph.nodes) {
    if (node.type !== 'TEST') continue;
    if (node.attributes?.concept === true) continue; // concept-only: no run artifact
    const parsed = TestRefSchema.safeParse(node.attributes?.testRef);
    if (!parsed.success) continue; // unbound TEST → R-19 surfaces it, nothing to scaffold
    stubs.push({ file: parsed.data.file, content: renderStub(node, parsed.data, verifiesByTest.get(node.uid) ?? []) });
  }
  return stubs;
}

function renderStub(node: GraphNode, ref: TestRef, verifies: string[]): string {
  const label = ref.case ?? `implement ${node.uid}`;
  const verifyNote = verifies.length > 0 ? ` — verifies ${verifies.join(', ')}` : '';
  return [
    '/**',
    ` * GENERATED STUB (CR-GC-205) — materialized from the graph binding ${node.uid}.`,
    ` * ${node.name}${verifyNote}.`,
    ' * Replace it.todo with the real test. Until then graph_tests resolves a real',
    ' * file (no phantom path) and vitest reports it pending, so the suite stays green.',
    ' */',
    "import { describe, it } from 'vitest';",
    '',
    `describe(${JSON.stringify(`${node.uid}: ${node.name}`)}, () => {`,
    `  it.todo(${JSON.stringify(label)});`,
    '});',
    '',
  ].join('\n');
}
