/**
 * Graph → Markdown/JSON Re-Exporter (CR-GC-113, MOD-docs).
 *
 * The single SSOT sync path: render the live graph back into commit-able docs.
 * Realizes FUNC-export-markdown / REQ-doc-export / REQ-pre-export-markdown /
 * REQ-post-export-markdown / FUNC-render-views; SCHEMA-markdown-view is the
 * MarkdownView schema below.
 *
 * EXPORT SOURCE = the harness IN-MEMORY authoritative working copy
 * (`harness.getGraph()`), NOT a fresh Kuzu reload.
 *   Kuzu is the durable QUERY INDEX, but its storage is LOSSY for arbitrary
 *   attributes — KuzuAdapter only persists declared property columns
 *   (name/description + declared props), so a raw Kuzu reload drops
 *   status/kinds/method/nested-`attributes`/etc. The full-fidelity graph is the
 *   JSON loaded by `importGraph()` and updated by the gate on every `mutate()`.
 *   Full-attribute Kuzu persistence is a known follow-up.
 *
 * `exportGraphJson` is the exact INVERSE of `GraphCodeHarness.importGraph`:
 *   element = { id: node.uid, type, name, description, ...node.attributes }
 *   trace   = { source: edge.sourceId, target: edge.targetId, type: edge.edgeType, ...edge.attributes }
 * Serialized canonically as `JSON.stringify(obj, null, 2) + "\n"` — the canonical
 * form the graph-integrity safety-net asserts, and byte-identical across calls.
 *
 * @author andreas@siglochconsulting
 */
import { z } from 'zod/v4';
import type { Graph, GraphNode, GraphEdge } from '@sigloch/graph-api-core';

// ---------------------------------------------------------------------------
// SCHEMA-markdown-view — app-specific, NOT in @sigloch/contracts.
// ---------------------------------------------------------------------------

/**
 * MarkdownView (SCHEMA-markdown-view): which generated, human-readable view to
 * render. View names mirror FLOW-export-request (spec/architecture/cr-list/
 * references); each renders deterministically with a GENERATED header.
 */
export const MarkdownViewSchema = z.enum(['spec', 'architecture', 'cr-list', 'references']);
export type MarkdownView = z.infer<typeof MarkdownViewSchema>;

/** All supported views, in deterministic order. */
export const MARKDOWN_VIEWS: readonly MarkdownView[] = MarkdownViewSchema.options;

// ---------------------------------------------------------------------------
// exportGraphJson — inverse of importGraph, canonical serialization.
// ---------------------------------------------------------------------------

/** Element shape in the materialized OntologyGraph JSON (`id` first, attrs spread). */
function nodeToElement(node: GraphNode): Record<string, unknown> {
  return {
    id: node.uid,
    type: node.type,
    name: node.name,
    description: node.description ?? '',
    // Spread attributes back to top-level, preserving their insertion order so
    // status/created_at/updated_at/kinds/method/nested-attributes land exactly
    // where importGraph put them. Inverse of `{ id, type, name, description, ...rest }`.
    ...node.attributes,
  };
}

/** Trace shape in the materialized OntologyGraph JSON. */
function edgeToTrace(edge: GraphEdge): Record<string, unknown> {
  return {
    source: edge.sourceId,
    target: edge.targetId,
    type: edge.edgeType,
    ...edge.attributes,
  };
}

/**
 * Reconstruct the committed JSON shape `{ elements, traces }` from a Graph and
 * serialize CANONICALLY (`JSON.stringify(obj, null, 2) + "\n"`).
 *
 * DETERMINISTIC: node/edge order is the graph's array order (the gate appends,
 * never reorders), attribute order is preserved by importGraph; two calls on the
 * same graph produce byte-identical output. This is the exact inverse of
 * `GraphCodeHarness.importGraph`, so import→export of the SSOT is byte-identical.
 */
export function exportGraphJson(graph: Graph): string {
  const elements = graph.nodes.map(nodeToElement);
  const traces = graph.edges.map(edgeToTrace);
  return JSON.stringify({ elements, traces }, null, 2) + '\n';
}

// ---------------------------------------------------------------------------
// exportMarkdown — deterministic views with a GENERATED header.
// ---------------------------------------------------------------------------

/** Marks a file as machine-generated; do-not-hand-edit. Stable across calls. */
function generatedHeader(title: string, subtitle: string): string {
  return [
    `<!-- GENERATED by @sigloch/graphcode exportMarkdown — DO NOT HAND-EDIT.`,
    `     Source of truth: docs/graph/graphcode.graph.json (the live graph).`,
    `     Re-render on model change: node scripts/export-graph.mjs -->`,
    ``,
    `# ${title}`,
    ``,
    `> GENERATED from \`docs/graph/graphcode.graph.json\` (SSOT). ${subtitle}`,
    ``,
  ].join('\n');
}

/** Stable lexicographic comparator on uid. */
function byUid(a: GraphNode, b: GraphNode): number {
  return a.uid.localeCompare(b.uid);
}

/** Stable comparator on [type, uid] for grouped listings. */
function byTypeThenUid(a: GraphNode, b: GraphNode): number {
  return a.type.localeCompare(b.type) || a.uid.localeCompare(b.uid);
}

/** A single-line, table-safe rendering of a description (no newlines / pipes). */
function cell(text: string): string {
  return (text ?? '').replace(/\s*\n\s*/g, ' ').replace(/\|/g, '/').trim();
}

function nodesOfTypes(graph: Graph, types: string[]): GraphNode[] {
  const set = new Set(types);
  return graph.nodes.filter((n) => set.has(n.type)).sort(byUid);
}

/** Overview/index of every element grouped by type (the `spec` view). */
function renderSpec(graph: Graph): string {
  const header = generatedHeader(
    'GraphCode — Modell-Spezifikation',
    'Alle Elemente nach Typ, sortiert nach uid. Deterministisch generiert.',
  );
  const sorted = [...graph.nodes].sort(byTypeThenUid);
  const lines: string[] = [header];
  lines.push(`Elemente: ${graph.nodes.length} · Traces: ${graph.edges.length}`, '');

  let currentType = '';
  for (const n of sorted) {
    if (n.type !== currentType) {
      currentType = n.type;
      lines.push('', `## ${currentType}`, '', '| uid | name | status | description |', '|---|---|---|---|');
    }
    const status = String(n.attributes['status'] ?? '');
    lines.push(`| \`${n.uid}\` | ${cell(n.name)} | ${status} | ${cell(n.description ?? '')} |`);
  }
  lines.push('');
  return lines.join('\n');
}

/** Module / function / system structure with allocate edges (the `architecture` view). */
function renderArchitecture(graph: Graph): string {
  const header = generatedHeader(
    'GraphCode — Architektur',
    'SYS / MOD / FUNC mit allocate-Zuordnung. Deterministisch generiert.',
  );
  const lines: string[] = [header];

  const structural = nodesOfTypes(graph, ['SYS', 'MOD', 'FUNC']);
  lines.push('## Strukturknoten', '', '| uid | type | name |', '|---|---|---|');
  for (const n of structural) {
    lines.push(`| \`${n.uid}\` | ${n.type} | ${cell(n.name)} |`);
  }
  lines.push('');

  // FUNC -allocate-> MOD assignment, sorted deterministically.
  const allocations = graph.edges
    .filter((e) => e.edgeType === 'allocate')
    .map((e) => ({ s: e.sourceId, t: e.targetId }))
    .sort((a, b) => a.s.localeCompare(b.s) || a.t.localeCompare(b.t));
  lines.push('## Allokation (FUNC -allocate-> MOD)', '', '| function | module |', '|---|---|');
  for (const a of allocations) {
    lines.push(`| \`${a.s}\` | \`${a.t}\` |`);
  }
  lines.push('');
  return lines.join('\n');
}

/** CR list (the `cr-list` view): every CR node with status. */
function renderCrList(graph: Graph): string {
  const header = generatedHeader(
    'GraphCode — Change-Requests',
    'Alle CR-Knoten, sortiert nach uid. Deterministisch generiert.',
  );
  const crs = nodesOfTypes(graph, ['CR']);
  const lines: string[] = [header];
  lines.push('| uid | name | status | description |', '|---|---|---|---|');
  for (const n of crs) {
    const status = String(n.attributes['status'] ?? '');
    lines.push(`| \`${n.uid}\` | ${cell(n.name)} | ${status} | ${cell(n.description ?? '')} |`);
  }
  lines.push('');
  return lines.join('\n');
}

/** Traceability references (the `references` view): every trace, sorted. */
function renderReferences(graph: Graph): string {
  const header = generatedHeader(
    'GraphCode — Traceability-References',
    'Alle Traces (source -type-> target), deterministisch sortiert.',
  );
  const traces = [...graph.edges]
    .map((e) => ({ s: e.sourceId, t: e.targetId, ty: e.edgeType }))
    .sort((a, b) => a.s.localeCompare(b.s) || a.ty.localeCompare(b.ty) || a.t.localeCompare(b.t));
  const lines: string[] = [header];
  lines.push('| source | type | target |', '|---|---|---|');
  for (const e of traces) {
    lines.push(`| \`${e.s}\` | ${e.ty} | \`${e.t}\` |`);
  }
  lines.push('');
  return lines.join('\n');
}

/**
 * Render a deterministic Markdown view of the graph with a GENERATED header.
 * Same (graph, view) → byte-identical output. Ordering is by uid / type / trace
 * key only (no insertion-order dependence). Renders no Mermaid, so the `()`/`|`
 * blank-diagram hazard does not apply; table cells are sanitized regardless.
 */
export function exportMarkdown(graph: Graph, view: MarkdownView): string {
  const v = MarkdownViewSchema.parse(view);
  switch (v) {
    case 'spec':
      return renderSpec(graph);
    case 'architecture':
      return renderArchitecture(graph);
    case 'cr-list':
      return renderCrList(graph);
    case 'references':
      return renderReferences(graph);
  }
}

/** Default file name for each view (under docs/views/). */
export const VIEW_FILENAMES: Record<MarkdownView, string> = {
  spec: 'spec.md',
  architecture: 'architecture.md',
  'cr-list': 'cr-list.md',
  references: 'references.md',
};
